name: Code coverage

on:
  push:
    branches:
      - "develdzop"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - name: Run unit/integration test
        run: yarn test --coverage
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          files: coverage/clover.xml

      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: coverage/clover.xml
      - name: Run e2e test
        run: |
          MARKETPLACE_COVERAGE=true yarn dev --mode test &
          sleep 10
          yarn e2e
      - name: Upload e2e tests coverage
        uses: codecov/codecov-action@v3
        with:
          files: coverage/clover.xml
